### ISSUE TITLE
also show open path

### ISSUE THREAD

**Issue by Nevu** [Nevu/PluginsForGlyphs_Nevu#4]
@schriftgestalt 

Hi Georg,

I will write directly to this repo, because my problem is also here ...

On this Plugin:

I tried to update this plugin by also show „open“ path and give them another color. This would give the possibility to create simple different meanings within _global-Glyph. I see there are differences between a „stroke/contour“ (left) and a „open path“ (right). See Screenshot.

<img width="825" alt="img_1" src="https://cloud.githubusercontent.com/assets/2456068/12435134/cea7b888-bf0b-11e5-8304-cd3d3b1a549b.png">

My first consideration was to copy those open path, reverse direction and close the now … like this :

```
for thisPath in thisLayer.paths:
if not thisPath.closed:
    thisPath.copy()
    thisLayer.paths.append(thisPath)
    thisPath.closed = True
```

But this was a quiet dirty way – for only straight segments – so, with dissatisfied results …

**Now, is there a way to convert all types of open paths to contours without "fill"?

**If there are no solutions with convert „open path“ to „contours“ – wich by the way seems not to be the best solution to this – is there another possibility in COCOA(?) to get those path, show them an re-color them?**

I would be grateful for any ideas, thx

**Comment by schriftgestalt** [comment]
there is layer.openBezierPath() Just do layer.openBezierPath().stroke()

**Comment by Nevu** [comment]
@schriftgestalt 
- -

Ok, your tip was great.
A open form works great but It seems that just draw the stroke of a open contour is not possible ...
- -

No there is another bug – I think there were some changes in the API ?! – 
The global glyph for now is not shown in the background of inactive glyphs. 
Also the original plugin before update has this bug ...

I looked at Deutschmarks 'Show Siblings' because the functions are nearly the same – and also his plugin doesn't show the siblings for now.

I work with Version 2.3b (837)

**Comment by Nevu** [comment]
@schriftgestalt thx for clean up code - for now, it should work
